                       AccuweatherDaemon \
                       AccuweatherWidget \
                       AccuweatherWidget_Main \
                       AllshareMediaServer \
                       AllSharePlay \
                       AllshareService \
                       AnalogClockSimple \
                       ApplicationsProvider \
                       Aurora \
                       AutomationTest_JBUP \
                       BackupRestoreConfirmation \
                       BadgeProvider \
                       BasicLiveWallpapers \
                       BCService \
                       Bluesea \
                       BluetoothAvrcp \
                       BluetoothMap \
                       BluetoothTest \
                       CapabilityManagerService \
                       CertInstaller \
                       ChatON_MARKET \
                       ChromeBookmarksSyncAdapter \
                       ClipboardSaveService \
                       ClockPackage \
                       CloudAgent \
                       ContextProvider \
                       crayon_physics \
                       CSC \
                       DataCreate_Q1_EUR_OPEN \
                       DefaultContainerService \
                       DigitalClock \
                       Divx \
                       DrmProvider \
                       Dropbox \
                       DropboxOOBE \
                       DSMForwarding \
                       DSMLawmo \
                       DualClockAnalog \
                       DualClockDigital \
                       EdmSysScopeService \
                       EdmVpnServices \
                       EnterprisePermissions \
                       FaceLock \
                       FactoryTest_Q1_EUR_OPEN \
                       FlashAnnotate \
                       FlashAnnotateSvc \
                       FlashBarService \
                       FmmDM \
                       FmmDS \
                       FmRadio \
                       FotaClient \
                       Gmail \
                       GmsCore \
                       GMS_Maps \
                       GoogleBackupTransport \
                       GoogleCalendarSyncAdapter \
                       GoogleContactsSyncAdapter \
                       GoogleFeedback \
                       GoogleLoginService \
                       GooglePartnerSetup \
                       GoogleServicesFramework \
                       GoogleTTS \
                       GroupCast \
                       HelpHub \
                       INDI_Server \
                       InputDevices \
                       InputEventApp_Q1_EUR_OPEN \
                       JobManager \
                       KeyChain \
                       Keystring_factory_JBUP \
                       Kies \
                       kieswifi \
                       Kobo \
                       lcdtest_Q1_EUR_OPEN \
                       LogsProvider \
                       MediaUploader \
                       Microbes \
                       minimode-res \
                       MobilePrint \
                       MobileTrackerEngineTwo \
                       MtpApplication \
                       MusicFX \
                       MusicPlayer \
                       NetworkLocation \
                       OceanWeather \
                       OmaCP \
                       OmaDrmPopup \
                       PackageInstaller \
                       PageBuddyNotiSvc \
                       PanningTryActually \
                       PaperArtist \
                       PCWClientS \
                       PhoneErrService \
                       Phonesky \
                       Phone_Util_Q1_EUR_OPEN \
                       PhotoWall \
                       PickUpTutorial \
                       PlusOne \
                       PolarisViewer \
                       PopupBrowser \
                       PopupuiReceiver \
                       Preconfig \
                       PreloadInstaller \
                       PressReader \
                       PRUI \
                       QuickSnote_Q1 \
                       ReadersHub \
                       ResourceManager \
                       SamsungApps \
                       SamsungAppsUNA3 \
                       SamsungCamera \
                       SamsungChineseIME_HKTW_Phone \
                       SamsungIME \
                       Samsungservice \
                       SamsungTTS \
                       SamsungWidget_FavoriteApp \
                       SamsungWidget_ProgramMonitor \
                       SChoice \
                       sCloudBackupApp \
                       sCloudBackupProvider \
                       sCloudDataRelay \
                       sCloudDataSync \
                       sCloudSyncBrowser \
                       sCloudSyncCalendar \
                       sCloudSyncContacts \
                       sCloudSyncSNote \
                       SecBluetooth \
                       SecBrowser \
                       SecCalculator2 \
                       SecCalendarProvider \
                       SecCalendar_Q1_SPen \
                       SecContacts \
                       SecContactsProvider \
                       SecDownloadProvider \
                       SecDownloadProviderUi \
                       SecEmail \
                       SecExchange \
                       SecFactoryPhoneTest \
                       SecFileShareClient \
                       SecFileShareServer \
                       SecGallery2_Galaxy \
                       SecHTMLViewer \
                       SecLauncher2 \
                       SecLiveWallpapersPicker \
                       SecMediaProvider \
                       SecMiniDiary \
                       SecMms \
                       SecNoteMyFiles \
                       SecOmaDownloadProvider \
                       SecPhone \
                       SecSettings \
                       SecSettingsProvider \
                       SecSetupWizard \
                       SecTelephonyProvider \
                       SecurityProvider \
                       SecWallpaperChooser \
                       SelfTestMode_Q1_EUR_OPEN \
                       SerialNumberLabelIndicator_JBUP \
                       serviceModeApp_Q1_EUR_OPEN \
                       SetupWizard \
                       SharedStorageBackup \
                       ShareShotService \
                       shutdown_JBUP \
                       SignatureLock \
                       SimpleAlarmClock \
                       SimpleFavoritesWidget \
                       SlideShow \
                       SmartcardService \
                       SMemoProvider_Q1 \
                       SMemo_Q1 \
                       Snote_Q1 \
                       Snote_Q1_Provider \
                       SNS \
                       SolitonS \
                       SPlannerAppWidget \
                       SPPPushClient_Prod \
                       Stk \
                       Street \
                       SuggestionService \
                       Superuser \
                       Swype \
                       SyncmlDM \
                       SyncmlDS \
                       SysScope \
                       SystemInfo_Q1_EUR_OPEN \
                       SystemUI \
                       Talk \
                       talkback \
                       TasksProvider \
                       TrimApp_phone \
                       TwDVFSApp \
                       UserDictionaryProvider \
                       Velvet \
                       VideoPlayer \
                       VoiceRecorder \
                       VoiceSearchStub \
                       voice_talk_Q1 \
                       VpnDialogs \
                       WAPPushManager \
                       WeatherWall \
                       WlanTest \
                       wssyncmlnps \
                       YahoonewsDaemon \
                       YahoonewsWidget \
                       YahoostockDaemon \
                       YahoostockWidget \
                       YouTube \
                       Zinio \
